#!/usr/bin/env sh
#
# Shell functions and aliases for using the "golang" dockerfiles image.

# Versions
DOCKERFILES_GOLANG_1_10_3_VERSION="1.10.3"
DOCKERFILES_GOLANG_1_10_VERSION="$DOCKERFILES_GOLANG_1_10_3_VERSION"
DOCKERFILES_GOLANG_1_VERSION="$DOCKERFILES_GOLANG_1_10_VERSION"
export DOCKERFILES_GOLANG_LATEST_VERSION="$DOCKERFILES_GOLANG_1_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_GOLANG_1_10_3_VERSION)
export DOCKERFILES_GOLANG_VERSIONS="$VERSIONS"

go() {
	_set_docker_run_image golang "${IMAGE_VERSION:-$DOCKERFILES_GOLANG_VERSIONS}" "${IMAGE_TAG:-""}"
	_set_docker_run_args go "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image go "$VERSIONS[@]"


unset DOCKERFILES_GOLANG_1_10_3_VERSION
unset DOCKERFILES_GOLANG_1_10_VERSION
unset DOCKERFILES_GOLANG_1_VERSION
unset VERSIONS
