#!/usr/bin/env sh
#
# Shell functions and aliases for using the "maven" dockerfiles image.

# Versions
DOCKERFILES_MAVEN_3_5_4_VERSION="3.5.4"
DOCKERFILES_MAVEN_3_5_VERSION="$DOCKERFILES_MAVEN_3_5_4_VERSION"
DOCKERFILES_MAVEN_3_VERSION="$DOCKERFILES_MAVEN_3_5_VERSION"
export DOCKERFILES_MAVEN_LATEST_VERSION="$DOCKERFILES_MAVEN_3_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_MAVEN_3_5_4_VERSION)
export DOCKERFILES_MAVEN_VERSIONS="$VERSIONS"

mvn() {
	_set_docker_run_image maven "${IMAGE_VERSION:-$DOCKERFILES_MAVEN_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args mvn "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image mvn "$VERSIONS[@]"

unset DOCKERFILES_MAVEN_3_5_4_VERSION
unset DOCKERFILES_MAVEN_3_5_VERSION
unset DOCKERFILES_MAVEN_3_VERSION
unset VERSIONS
