#!/usr/bin/env sh
#
# Shell functions and aliases for using the "nodejs" dockerfiles image.

# Versions
DOCKERFILES_NODEJS_8_11_3_VERSION="8.11.3"
DOCKERFILES_NODEJS_8_11_VERSION="$DOCKERFILES_NODEJS_8_11_3_VERSION"
DOCKERFILES_NODEJS_8_VERSION="$DOCKERFILES_NODEJS_8_11_VERSION"
export DOCKERFILES_NODEJS_LATEST_VERSION="$DOCKERFILES_NODEJS_8_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_NODEJS_8_11_3_VERSION)
export DOCKERFILES_NODEJS_VERSIONS="$VERSIONS"

node() {
	_set_docker_run_image nodejs "${IMAGE_VERSION:-$DOCKERFILES_NODEJS_VERSIONS}" "${IMAGE_TAG:-""}"
	_set_docker_run_args node "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image node "$VERSIONS[@]"

unset DOCKERFILES_NODEJS_8_11_3_VERSION
unset DOCKERFILES_NODEJS_8_11_VERSION
unset DOCKERFILES_NODEJS_8_VERSION
unset VERSIONS
