#!/usr/bin/env sh
#
# Shell functions and aliases for using the "python3" dockerfiles image.

# Versions
DOCKERFILES_PYTHON_3_6_4_VERSION="2.7.15"
DOCKERFILES_PYTHON_3_6_VERSION="$DOCKERFILES_PYTHON_3_6_4_VERSION"
DOCKERFILES_PYTHON_3_VERSION="$DOCKERFILES_PYTHON_3_6_VERSION"
export DOCKERFILES_PYTHON_3_LATEST_VERSION="$DOCKERFILES_PYTHON_3_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_PYTHON_2_7_15_VERSION)
export DOCKERFILES_PYTHON_3_VERSIONS="$VERSIONS"

python3() {
	_set_docker_run_image python "${IMAGE_VERSION:-$DOCKERFILES_PYTHON_3_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args python3 "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image python python3 "$VERSIONS[@]"

unset DOCKERFILES_PYTHON_3_6_4_VERSION
unset DOCKERFILES_PYTHON_3_6_VERSION
unset DOCKERFILES_PYTHON_3_VERSION
unset VERSIONS
