#!/usr/bin/env sh
#
# Shell functions and aliases for using the "sbt" dockerfiles image.

# Versions
DOCKERFILES_SBT_1_1_6_VERSION="1.1.6"
DOCKERFILES_SBT_1_1_VERSION="$DOCKERFILES_SBT_1_1_6_VERSION"
DOCKERFILES_SBT_1_VERSION="$DOCKERFILES_SBT_1_1_VERSION"
export DOCKERFILES_SBT_LATEST_VERSION="$DOCKERFILES_SBT_1_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_SBT_1_1_6_VERSION)
export DOCKERFILES_SBT_VERSIONS="$VERSIONS"

sbt() {
	_set_docker_run_image sbt "${IMAGE_VERSION:-$DOCKERFILES_SBT_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args sbt "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image sbt "$VERSIONS[@]"

unset DOCKERFILES_SBT_1_1_6_VERSION
unset DOCKERFILES_SBT_1_1_VERSION
unset DOCKERFILES_SBT_1_VERSION
unset VERSIONS
