#!/usr/bin/env sh
#
# Shell functions and aliases for using the "scala" dockerfiles image.

# Versions
DOCKERFILES_SCALA_2_12_6_VERSION="2.12.6"
DOCKERFILES_SCALA_2_12_VERSION="$DOCKERFILES_SCALA_2_12_6_VERSION"
DOCKERFILES_SCALA_2_VERSION="$DOCKERFILES_SCALA_2_12_VERSION"
export DOCKERFILES_SCALA_LATEST_VERSION="$DOCKERFILES_SCALA_2_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_SCALA_2_12_6_VERSION)
export DOCKERFILES_SCALA_VERSIONS="$VERSIONS"

scala() {
	_set_docker_run_image scala "${IMAGE_VERSION:-$DOCKERFILES_SCALA_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args scala "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image scala scala "$VERSIONS[@]"

unset DOCKERFILES_SCALA_2_12_6_VERSION
unset DOCKERFILES_SCALA_2_12_VERSION
unset DOCKERFILES_SCALA_2_VERSION
unset VERSIONS
