#!/usr/bin/env sh
#
# Shell functions and aliases for using the "shellcheck" dockerfiles image.

# Versions
DOCKERFILES_SHELLCHECK_0_4_7_VERSION="0.4.7"
DOCKERFILES_SHELLCHECK_0_4_VERSION="$DOCKERFILES_SHELLCHECK_0_4_7_VERSION"
DOCKERFILES_SHELLCHECK_0_VERSION="$DOCKERFILES_SHELLCHECK_0_4_VERSION"
export DOCKERFILES_SHELLCHECK_LATEST_VERSION="$DOCKERFILES_SHELLCHECK_0_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_SHELLCHECK_0_4_7_VERSION)
export DOCKERFILES_SHELLCHECK_VERSIONS="$VERSIONS"

shellcheck() {
	_set_docker_run_image shellcheck "${IMAGE_VERSION:-$DOCKERFILES_SHELLCHECK_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args shellcheck "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image shellcheck shellcheck "$VERSIONS[@]"

unset DOCKERFILES_SHELLCHECK_0_4_7_VERSION
unset DOCKERFILES_SHELLCHECK_0_4_VERSION
unset DOCKERFILES_SHELLCHECK_0_VERSION
unset VERSIONS
