#!/usr/bin/env sh
#
# Shell functions and aliases for using the "travis" dockerfiles image.

# Versions
DOCKERFILES_TRAVIS_1_8_8_VERSION="1.8.8"
DOCKERFILES_TRAVIS_1_8_VERSION="$DOCKERFILES_TRAVIS_1_8_8_VERSION"
DOCKERFILES_TRAVIS_1_VERSION="$DOCKERFILES_TRAVIS_1_8_VERSION"
export DOCKERFILES_TRAVIS_LATEST_VERSION="$DOCKERFILES_TRAVIS_1_VERSION"

# shellcheck disable=2039
declare -a VERSIONS=($DOCKERFILES_TRAVIS_1_8_8_VERSION)
export DOCKERFILES_TRAVIS_VERSIONS="$VERSIONS"

travis() {
	_set_docker_run_image travis "${IMAGE_VERSION:-$DOCKERFILES_TRAVIS_LATEST_VERSION}" "${IMAGE_TAG:-""}"
	_set_docker_run_args travis "$@"

	docker run \
		--interactive \
		--tty \
		--rm \
		--env-file "$DOCKERFILES_ENV_FILE" \
		--volume "$(pwd):$DOCKERFILES_WORKDIR" \
		--workdir "$DOCKERFILES_WORKDIR" \
		$DOCKER_RUN_IMAGE $DOCKER_RUN_ARGS
}

_set_aliases_for_image travis travis "$VERSIONS[@]"

unset DOCKERFILES_TRAVIS_1_8_8_VERSION
unset DOCKERFILES_TRAVIS_1_8_VERSION
unset DOCKERFILES_TRAVIS_1_VERSION
unset VERSIONS
